
---
# ansible compute implementation
# - import_playbook: component_playbooks/gcp_compute_configurations.yml
# - import_playbook: ansible_components/playbooks/role_base.yml
#- import_playbook: playbooks/role_base.yml
#- import_playbook: playbooks/app_installer.yml
#- import_playbook: playbooks/pub_sub_base.yml
- name: Enterprise Kubernates Setup
  hosts: all
  gather_facts: false
  tasks:
#    - include_tasks: ../../roles/yantram/tasks/gcp/gcp_network_address_configurations.yml
#    - import_tasks: roles/yantram/tasks/gcp/gcp_disk_configurations.yml
    - import_tasks: roles/yantram_kubernates/tasks/main.yml
    - import_tasks: roles/yantram_kubernates/tasks/kubernates/kubernates_configurations.yml
#    - import_tasks: roles/yantram/tasks/gcp/gcp_compute_configurations.yml
#    - import_tasks: roles/yantram/tasks/vm_compute_post.yml

#- import_playbook: playbooks/app_installer.yml
#    - include: geerlingguy.docker wp_user=timmy
#    - include: wordpress.yml wp_user=alice
#    - include: wordpress.yml wp_user=bob


